### ISSUE TITLE
get pushToken

### ISSUE THREAD

**Issue by xiaoyintoken** [batikansosun/iOS-16-Live-Activities-Dynamic-Island#1]
I get pushtoken is nil all the time, how do you get it

**Comment by wangyangcc** [comment]
You can get pushtoken in `func update(activity: Activity<GroceryDeliveryAppAttributes>) `method

**Comment by wangyangcc** [comment]
@xiaoyintoken You can get pushtoken in func update(activity: Activity<GroceryDeliveryAppAttributes>) method

**Comment by wangyangcc** [comment]
@xiaoyintoken You can get pushtoken in `func update(activity: Activity<GroceryDeliveryAppAttributes>)` method

**Comment by batikansosun** [comment]
> I get pushtoken is nil all the time, how do you get it

Hi [xiaoyintoken](https://github.com/xiaoyintoken), 

Every activity has push token data to update its content via Remote Push Notification. You can access token data like the below code.

Eligibility Conditions

Push Notifications Capability
Background Modes - Remote Notifications
Push Notification Request Authorization
Physical Device 
OR
"To test remote push notifications for Live Activities in Simulator, use a [Mac model with the Apple T2 Security Chip](https://support.apple.com/en-us/HT208862) or a [Mac with Apple silicon](https://support.apple.com/en-us/HT211814) that runs macOS 13 or later."


`var activities = Activity<GroceryDeliveryAppAttributes>.activities`
`let pushTokenData = activities.first?.pushToken`

**Comment by batikansosun** [comment]
I'm going to close the issue. If you get any errors reopen it.
