### ISSUE TITLE
Closure containing control flow statement cannot be used with result builder 'WidgetBundleBuilder'

### ISSUE THREAD

**Issue by purgeyao** [batikansosun/iOS-16-Live-Activities-Dynamic-Island#2]
```
@main
struct Widgets: WidgetBundle {
    var body: some Widget {
        if #available(iOS 16.1, *) {Closure containing control flow statement cannot be used with result builder 'WidgetBundleBuilder'
            GroceryDeliveryApp()
        }
    }
}
```
 if #available(iOS 16.1, *) {  
Closure containing control flow statement cannot be used with result builder 'WidgetBundleBuilder'
Hi, do I have any good solutions for this

**Comment by batikansosun** [comment]
@purgeyao  Hi, sorry for the delay. Did you edit the GroceryDeliveryApp method or build it with Xcode v14.1 Beta?

**Comment by purgeyao** [comment]
@batikansosun  Version 14.0.1 (14A400)

**Comment by batikansosun** [comment]
@purgeyao   It's a different version. You have to build with Xcode 14.1 Beta. You can find this specific Xcode version download link here: https://xcodereleases.com

**Comment by batikansosun** [comment]
I'm going to close the issue. If you get any errors reopen it.
